/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package telegrambots;

import org.telegram.telegrambots.ApiContextInitializer;
import org.telegram.telegrambots.meta.TelegramBotsApi;
import org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException;

public class App {

    public static void main(String[] args) {
        //        Initialize Api Context
        ApiContextInitializer.init();
//        Instantiate Telegram Bots Api
        TelegramBotsApi botsApi = new TelegramBotsApi();
//        Register bot
        try {
            botsApi.registerBot(new JoyReactorBot());
        } catch (TelegramApiRequestException e) {
            e.printStackTrace();
        }
    }
}
